apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: noprod-child-3scale-install
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  env: noprod
          - list:
              elements:
                - namespace: 3scale
                - namespace: 3scale-tenant-dev
                - namespace: 3scale-tenant-testing
  template:
    metadata:
      name: "{{name}}-{{namespace}}-install"
    spec:
      project: default
      source:
        repoURL: https://github.com/lfalero14/gitops-middleware-operator-install.git
        targetRevision: HEAD
        path: "./manifests/middleware-3scale/overlays/noprod/{{namespace}}"
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        #automated:
        #  prune: true
        #  selfHeal: true
        #  allowEmpty: false
