apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: noprod-child-logging-install
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: noprod
  template:
    metadata:
      name: "{{name}}-logging-install"
    spec:
      project: default
      source:
        repoURL: https://github.com/lfalero14/gitops-middleware-operator-install.git
        targetRevision: HEAD
        path: "./manifests/middleware-logging/overlays/noprod"
        kustomize:
          patches:
            - target:
                kind: RoleBinding
                name: hook-binding
              patch: |-
                - op: add
                  path: /subjects/0/namespace
                  value: "logging"
      destination:
        server: "{{server}}"
        namespace: "logging"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        #automated:
        #  prune: true
        #  selfHeal: true
        #  allowEmpty: false
