apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: noprod-child-apicast-install
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: noprod
  template:
    metadata:
      name: "{{name}}-apicast-install"
    spec:
      project: default
      source:
        repoURL: https://github.com/lfalero14/gitops-middleware-operator-install.git
        targetRevision: develop
        path: "./manifests/middleware-apicast/overlays/noprod"
      destination:
        server: "{{server}}"
        namespace: "3scale"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        #automated:
        # prune: true
        # selfHeal: true
