apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: noprod-child-database-install
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: noprod
  template:
    metadata:
      name: "{{name}}-database-install"
    spec:
      project: default
      source:
        repoURL: https://github.com/lfalero14/gitops-middleware-operator-install.git
        targetRevision: HEAD
        path: "./manifests/middleware-database"
      destination:
        server: "{{server}}"
        namespace: "database"
        #automated:
        #  prune: true
        #  selfHeal: true
        #  allowEmpty: false
