apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: noprod-child-apicast-install
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  env: noprod
          - list:
              elements:
                - namespace: 3scale
                - namespace: 3scale-tenant-dev
                - namespace: 3scale-tenant-testing
  template:
    metadata:
      name: "{{name}}-{{namespace}}-apicast"
    spec:
      project: default
      source:
        repoURL: https://github.com/lfalero14/gitops-middleware-operator-install.git
        targetRevision: develop
        path: "./manifests/middleware-apicast/overlays/noprod"
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        #automated:
          #prune: true
          #selfHeal: true
