apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: noprod-child-observability-install
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: noprod
  template:
    metadata:
      name: "{{name}}-observability-install"
    spec:
      project: default
      source:
        repoURL: https://github.com/lfalero14/gitops-middleware-operator-install.git
        targetRevision: HEAD
        path: "./manifests/middleware-observability/overlays/noprod"
      destination:
        server: "{{server}}"
        namespace: "openshift-cluster-observability-operator"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        #automated:
        #  prune: true
        #  selfHeal: true
        #  allowEmpty: false
