apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noprod-root-operator-install
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/lfalero14/gitops-middleware-operator-install.git
    targetRevision: HEAD
    path: ./app-of-apps/child-apps/noprod
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: openshift-gitops-local-binding
