apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hook-role
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
  - apiGroups: ["apps.3scale.net"]
    resources: ["apimanagers"]
    verbs: ["get", "list"]

  - apiGroups: ["capabilities.3scale.net"]
    resources: ["tenants"]
    verbs: ["get", "list"]
