apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-child-apicast-install
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: prod
  template:
    metadata:
      name: "{{name}}-apicast-install"
    spec:
      project: default
      source:
        repoURL: https://github.com/lfalero14/gitops-middleware-operator-install.git
        targetRevision: HEAD
        path: "./manifests/middleware-apicast/overlays/prod"
        kustomize:
          patches:
            - target:
                kind: OperatorGroup
                name: apicast-operator
              patch: |-
                - op: add
                  path: /spec/targetNamespaces/0
                  value: "apicast-gateway"
            - target:
                kind: RoleBinding
                name: hook-binding
              patch: |-
                - op: add
                  path: /subjects/0/namespace
                  value: "apicast-gateway"
      destination:
        server: "{{server}}"
        namespace: "apicast-gateway"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
