apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-child-3scale-install
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  env: prod
          - list:
              elements:
                - namespace: 3scale
                - namespace: 3scale-tenant-prod
  template:
    metadata:
      name: "{{name}}-{{namespace}}-install"
    spec:
      project: default
      source:
        repoURL: https://github.com/lfalero14/gitops-middleware-operator-install.git
        targetRevision: develop
        path: "./manifests/middleware-3scale/overlays/prod"
        kustomize:
          patches:
            - target:
                kind: Namespace
                name: 3scale-tmp
              patch: |-
                - op: add
                  path: /metadata/name
                  value: "{{namespace}}"
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        #automated:
        #prune: true
        #selfHeal: true
