kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-csi #change
  volumeMode: Filesystem
