apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base
resources:
  - operator_namespace.yaml
  - operator_operatorgroup.yaml
  - operator_subscription.yaml
  - operator_post-hook.yaml

#patchesStrategicMerge:
#  - application_role-binding.yaml
#  - zync-que.yaml

configMapGenerator:
  - name: zync-ca-bundle
    files:
      - certs/zync.pem

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: zync-que.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: zync-que
      labelSelector: "threescale_component_element=zync-que"
  - path: application_role-binding.yaml
