apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../middleware-base
resources:
  - operator_namespace.yaml
  - operator_operatorgroup.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: rhbk-operator
    target:
      group: batch
      version: v1
      kind: Job
      name: post-sync-check-keycloak-operator
